/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buzzquizworldui;

import buzzquizworld.object.model.Game;
import buzzquizworld.object.model.User;
import buzzquizworld.object.model.ui.GameFactory;
import buzzquizworld.object.model.ui.UiRightAnswerGame;
import buzzquizworldui.translations.UiTranslator;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author Jackie
 */
public class NewGamePanel extends javax.swing.JPanel {
    private MainFrame frame;
    
    /**
     * Creates new form NewGamePanel
     */
    public NewGamePanel(MainFrame frame) {
        initComponents();
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        SinglePlayerRadioButton = new javax.swing.JRadioButton();
        MultiPlayerRadioButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        WelcomeLabel = new javax.swing.JLabel();
        StartGameButton = new javax.swing.JButton();
        user1Name = new javax.swing.JTextField();
        user1Label = new javax.swing.JLabel();
        user2Label = new javax.swing.JLabel();
        user2Name = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        buttonGroup1.add(SinglePlayerRadioButton);
        SinglePlayerRadioButton.setLabel("Single Player");
        SinglePlayerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinglePlayerRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(MultiPlayerRadioButton);
        MultiPlayerRadioButton.setLabel("Multi Player");
        MultiPlayerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiPlayerRadioButtonActionPerformed(evt);
            }
        });

        WelcomeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WelcomeLabel.setText("Welcome to buzz quiz wolrd");

        StartGameButton.setText("Start");
        StartGameButton.setEnabled(false);
        StartGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGameButtonActionPerformed(evt);
            }
        });

        user1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user1NameActionPerformed(evt);
            }
        });

        user1Label.setText("jLabel1");

        user2Label.setText("jLabel1");

        user2Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user2NameActionPerformed(evt);
            }
        });

        userLabel.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(StartGameButton)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(userLabel)
                        .addGap(18, 18, 18)
                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WelcomeLabel)
                                    .addComponent(MultiPlayerRadioButton)
                                    .addComponent(SinglePlayerRadioButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(user1Label)
                                        .addGap(18, 18, 18)
                                        .addComponent(user1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(user2Label)
                                        .addGap(18, 18, 18)
                                        .addComponent(user2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 113, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(WelcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MultiPlayerRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user1Label)
                    .addComponent(user2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user2Label))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SinglePlayerRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel))
                .addGap(12, 12, 12)
                .addComponent(StartGameButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SinglePlayerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinglePlayerRadioButtonActionPerformed
        StartGameButton.setEnabled(true);
    }//GEN-LAST:event_SinglePlayerRadioButtonActionPerformed

    private void MultiPlayerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiPlayerRadioButtonActionPerformed
        StartGameButton.setEnabled(true);
    }//GEN-LAST:event_MultiPlayerRadioButtonActionPerformed

    private void StartGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGameButtonActionPerformed
        try {
            Game game;
            if(this.MultiPlayerRadioButton.isSelected()){
                game = GameFactory.SelectRandomGameMode(true);
                game.setUser1(new User(this.user1Name.getText(), 1000, 0, 0));
                game.setUser2(new User(this.user2Name.getText(), 1000, 0, 0));
            } else{    
                game = GameFactory.SelectRandomGameMode(false);
                game.setUser1(new User(this.userName.getText(), 1000, 0, 0));
            }
            this.frame.setGame(game);
            this.setVisible(false);
            this.frame.OpenQuestionPanel();
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(NewGamePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(NewGamePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewGamePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_StartGameButtonActionPerformed

    private void user1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user1NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user1NameActionPerformed

    private void user2NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user2NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user2NameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton MultiPlayerRadioButton;
    private javax.swing.JRadioButton SinglePlayerRadioButton;
    private javax.swing.JButton StartGameButton;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel user1Label;
    private javax.swing.JTextField user1Name;
    private javax.swing.JLabel user2Label;
    private javax.swing.JTextField user2Name;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables

    public JRadioButton getSinglePlayerRadioButton() {
        return SinglePlayerRadioButton;
    }

    public JButton getStartGameButton() {
        return StartGameButton;
    }

    public JLabel getWelcomeLabel() {
        return WelcomeLabel;
    }

    
}
