/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buzzquizworldui;

import buzzquizworld.object.model.User;
import java.awt.Color;

/**
 *
 * @author Jackie
 */
public class UserPanel extends javax.swing.JPanel {

    User user1;

    /**
     * Creates new form UserPanel
     */
    public UserPanel(User user1) {

        this.user1 = user1;
        initComponents();
        this.ShowUserDetails();
    }

    public void ShowUserDetails() {
        this.UserPanelUserName.setText(this.user1.getName());
        this.UserPoints.setText(String.valueOf(this.user1.getPoints()));
    }
    
    public void isActive(boolean active){
        currentPlayer.setOpaque(true);
        currentPlayer.setBackground(active?Color.GREEN:this.getBackground());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserPanelUserName = new javax.swing.JLabel();
        UserPoints = new javax.swing.JLabel();
        PointLabel = new javax.swing.JLabel();
        UserLabel = new javax.swing.JLabel();
        currentPlayer = new javax.swing.JLabel();

        UserPanelUserName.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        UserPanelUserName.setText("jLabel1");

        UserPoints.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        UserPoints.setText("jLabel2");

        PointLabel.setText("jLabel1");

        UserLabel.setText("jLabel1");

        currentPlayer.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UserLabel)
                    .addComponent(PointLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserPanelUserName)
                    .addComponent(UserPoints))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(currentPlayer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserPanelUserName)
                            .addComponent(UserLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserPoints)
                            .addComponent(PointLabel))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PointLabel;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JLabel UserPanelUserName;
    private javax.swing.JLabel UserPoints;
    private javax.swing.JLabel currentPlayer;
    // End of variables declaration//GEN-END:variables

}
